name: Server

on:
  push:
    branches: [ "main" ]
    paths: ["nightserv/**"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          nightserv/
          .github/
    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./nightserv/target/
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-${{ hashFiles('./nightserv/Cargo.lock') }}-cache
    - name: Build
      run: |
        cd nightserv
        sudo apt-get install musl-tools
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --verbose --target x86_64-unknown-linux-musl
    # from https://stackoverflow.com/questions/68412832/github-actions-copy-files-to-vps?rq=3
    - name: Deploy (quit server)
      uses: ./.github/runssh
      with:
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        cmd: |
          cd ${{ secrets.SSH_PATH }}/nightserv
          mkdir -p ./target/release
          screen -S hacknight -X quit || true
          rm ./target/release/nightserv || true
    - name: Deploy (start server)
      uses: ./.github/runssh
      with:
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        file: nightserv/target/x86_64-unknown-linux-musl/release/nightserv
        dest: ${{ secrets.SSH_PATH }}/nightserv/target/release/nightserv
        cmd: |
          cd ${{ secrets.SSH_PATH }}/nightserv
          screen -S hacknight -d -m ./target/release/nightserv
